config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#         new_pilot_session GET    /pilots/sign_in(.:format)                                                                devise/sessions#new
#             pilot_session POST   /pilots/sign_in(.:format)                                                                devise/sessions#create
#     destroy_pilot_session DELETE /pilots/sign_out(.:format)                                                               devise/sessions#destroy
#        new_pilot_password GET    /pilots/password/new(.:format)                                                           devise/passwords#new
#       edit_pilot_password GET    /pilots/password/edit(.:format)                                                          devise/passwords#edit
#            pilot_password PATCH  /pilots/password(.:format)                                                               devise/passwords#update
#                           PUT    /pilots/password(.:format)                                                               devise/passwords#update
#                           POST   /pilots/password(.:format)                                                               devise/passwords#create
# cancel_pilot_registration GET    /pilots/cancel(.:format)                                                                 devise/registrations#cancel
#    new_pilot_registration GET    /pilots/sign_up(.:format)                                                                devise/registrations#new
#   edit_pilot_registration GET    /pilots/edit(.:format)                                                                   devise/registrations#edit
#        pilot_registration PATCH  /pilots(.:format)                                                                        devise/registrations#update
#                           PUT    /pilots(.:format)                                                                        devise/registrations#update
#                           DELETE /pilots(.:format)                                                                        devise/registrations#destroy
#                           POST   /pilots(.:format)                                                                        devise/registrations#create
#                      root GET    /                                                                                        site/pages#index
#     site_backoffice_index GET    /site/backoffice/index(.:format)                                                         site/backoffice#index
#               admin_ranks GET    /admin/ranks(.:format)                                                                   admin/ranks#index
#                           POST   /admin/ranks(.:format)                                                                   admin/ranks#create
#            new_admin_rank GET    /admin/ranks/new(.:format)                                                               admin/ranks#new
#           edit_admin_rank GET    /admin/ranks/:id/edit(.:format)                                                          admin/ranks#edit
#                admin_rank GET    /admin/ranks/:id(.:format)                                                               admin/ranks#show
#                           PATCH  /admin/ranks/:id(.:format)                                                               admin/ranks#update
#                           PUT    /admin/ranks/:id(.:format)                                                               admin/ranks#update
#                           DELETE /admin/ranks/:id(.:format)                                                               admin/ranks#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  namespace :admin do
    get 'routes/index'
  end
  devise_for :pilots
  
  root 'site/pages#index'
  
  namespace :site do
    get 'pages/pilots'
  end
  
  namespace :admin do
    root 'home#index'
    resources :ranks
    resources :pilots
    resources :airports
    resources :aircrafts
    resources :aircraft_types
    resources :routes
  end
end

app/views/site/pages/shared/_about.html.haml
%section#about.page-section.bg-primary
  .container
    .row.justify-content-center
      .col-lg-8.text-center
        %h2.text-white.mt-0 Welcome to Virtual Varig-Cruzeiro
        %hr.divider.light.my-4/
        %p.text-white-50.mb-4 We are a Virtual Airlines. We simulate online flights. We have no ties to real airlines.
        %a.btn.btn-light.btn-xl.js-scroll-trigger{:href => "#services"} Our Rules

app/views/site/pages/shared/_contact.html.haml
%section#contact.page-section
  .container
    .row.justify-content-center
      .col-lg-8.text-center
        %h2.mt-0 Contact us!
        %hr.divider.my-4/
        %p.text-muted.mb-5 Send your message to our team and let's talk about any ideas
    .row
      .col-lg-4.ml-auto.text-center.mb-5.mb-lg-0
        %i.fa.fa-whatsapp.fa-3x.mb-3.text-muted
        %div
          %a{href: 'https://chat.whatsapp.com/F2tfWlBcAdo6VqTEHjJCaE', target: '_blank'} Whatspp
      .col-lg-4.mr-auto.text-center
        %i.fa.fa-envelope.fa-3x.mb-3.text-muted
        / Make sure to change the email address in anchor text AND the link below!
        %a.d-block{:href => "mailto:virtual@varig-cruzeiro.com.br"} virtual@varig-cruzeiro.com.br

app/views/site/pages/shared/_estatistics.html.haml
%section#estatistics.page-section
  .container
    %h2.text-center.mt-0 Our statistics
    %hr.divider.my-4/
    .row
      .col-lg-3.col-md-6.text-center
        .mt-5
          %i.fa.fa-4x.fa-plane.text-primary.mb-4{title: 'Aircrafts'}
          %h3.h4.mb-2 10
          %p.text-muted.mb-0 Our themes are updated regularly to keep them bug free!
      .col-lg-3.col-md-6.text-center
        .mt-5
          %i.fa.fa-4x.fa-users.text-primary.mb-4{title: 'Pilots'}
          %h3.h4.mb-2 50
          %p.text-muted.mb-0 All dependencies are kept current to keep things fresh.
      .col-lg-3.col-md-6.text-center
        .mt-5
          %i.fa.fa-4x.fa-location-arrow.text-primary.mb-4{title: 'Routes'}
          %h3.h4.mb-2 500
          %p.text-muted.mb-0 You can use this design as is, or you can make changes!
      .col-lg-3.col-md-6.text-center
        .mt-5
          %i.fa.fa-4x.fa-clock-o.text-primary.mb-4{title: 'Time of Flight'}
          %h3.h4.mb-2 + 100000
          %p.text-muted.mb-0 Is it really open source if it's not made with love?

app/views/site/pages/shared/_fleet.html.haml
%section#fleet
  .container-fluid.p-0
    .row.no-gutters
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/1.jpg')}"}
          = image_tag 'fleet/1.jpg', class: 'img-fluid'
          .fleet-box-caption
            .project-category.text-white-50
              Category
            .project-name
              Project Name
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/2.jpg')}"}
          = image_tag 'fleet/2.jpg', class: 'img-fluid'
          .fleet-box-caption
            .project-category.text-white-50
              Category
            .project-name
              Project Name
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/3.jpg')}"}
          = image_tag 'fleet/3.jpg', class: 'img-fluid'
          .fleet-box-caption
            .project-category.text-white-50
              Category
            .project-name
              Project Name
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/4.jpg')}"}
          = image_tag 'fleet/4.jpg', class: 'img-fluid'
          .fleet-box-caption
            .project-category.text-white-50
              Category
            .project-name
              Project Name
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/5.jpg')}"}
          = image_tag 'fleet/5.jpg', class: 'img-fluid'
          .fleet-box-caption
            .project-category.text-white-50
              Category
            .project-name
              Project Name
      .col-lg-4.col-sm-6
        %a.fleet-box{href: "#{image_path('fleet/6.jpg')}"}
          = image_tag 'fleet/6.jpg', class: 'img-fluid'
          .fleet-box-caption.p-3
            .project-category.text-white-50
              Category
            .project-name
              Project Name

app/views/site/pages/shared/_header.html.haml
%header.masthead
  .container.h-100
    .row.h-100.align-items-center.justify-content-center.text-center
      .col-lg-10.align-self-end
        %h1.text-uppercase.text-white.font-weight-bold IT WAS NEVER SO EASY TO FLY
        %hr.divider.my-4
      .col-lg-8.align-self-baseline
        %p.text-white-75.font-weight-light.mb-5 Varig-Cruzeiro is a non-profit online air simulation organization.
        - unless pilot_signed_in?
          = link_to new_pilot_registration_path, class: 'btn btn-outline-light btn-lg btn-xl js-scroll-trigger' do
            %i.fa.fa-plane
            Sign-up

app/views/site/pages/shared/_last_pilots.html.haml
%section.page-section.bg-light
  .container
    .row.justify-content-center
      .col-lg-8.text-center
        %h2.mt-0 Last Pilots
        %hr.divider.my-4/
    .row
      .col
        .table-responsive
          %table.table.table-striped.table-sm
            %thead
              %tr.text-center
                %th{:scope => "col"} #
                %th{:scope => "col"} Callsign
                %th{:scope => "col"} Name
                %th{:scope => "col"} Rank
                %th{:scope => "col"} Country
                %th{:scope => "col"} City
                %th{:scope => "col"} IVAO
                %th{:scope => "col"} VATSIM
                %th{:scope => "col"} Hours
                %th{:scope => "col"} Location
                %th{:scope => "col"} Status
            %tbody
              - @last_pilots.each_with_index do |pilot, index|
                %tr.text-center
                  %th{:scope => "row"}=index+1
                  %td=pilot.callsign
                  %td=pilot.name
                  %td=pilot.rank.present? ? pilot.rank.description : ''
                  %td=pilot.country
                  %td=pilot.city
                  %td=pilot.ivao
                  %td=pilot.vatsim
                  %td=pilot.hours or 0
                  %td=pilot.location
                  %td=pilot.status.present? ? pilot.status : '-'